// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Bichocubo_a60afc6680ffaba4f99a82d970f62c1fIndex = 0;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Bichocubo_a60afc6680ffaba4f99a82d970f62c1f", 0 },

		};
	}
}
